import { Recipe, MealPlan } from "@/types"

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    title: "Mediterranean Grilled Salmon",
    description: "Fresh Atlantic salmon with herbs, lemon, and a light olive oil drizzle. Perfect for a healthy weeknight dinner.",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "Easy",
    category: "Dinner",
    cuisine: "Mediterranean",
    ingredients: [
      { name: "Salmon fillets", amount: "4", unit: "pieces" },
      { name: "Olive oil", amount: "3", unit: "tbsp" },
      { name: "Lemon", amount: "2", unit: "whole" },
      { name: "Fresh dill", amount: "1/4", unit: "cup" },
      { name: "Garlic", amount: "4", unit: "cloves" },
    ],
    instructions: [
      "Preheat grill to medium-high heat.",
      "Season salmon with salt, pepper, and minced garlic.",
      "Drizzle with olive oil and squeeze lemon juice over fillets.",
      "Grill for 4-5 minutes per side until cooked through.",
      "Garnish with fresh dill and serve immediately.",
    ],
    nutritionInfo: {
      calories: 320,
      protein: 34,
      carbs: 2,
      fat: 19,
      fiber: 0,
    },
    tags: ["healthy", "high-protein", "low-carb", "quick"],
    isFavorite: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    title: "Classic Margherita Pizza",
    description: "Authentic Italian pizza with San Marzano tomatoes, fresh mozzarella, and basil on a crispy thin crust.",
    image: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=800&q=80",
    prepTime: 30,
    cookTime: 15,
    servings: 2,
    difficulty: "Medium",
    category: "Dinner",
    cuisine: "Italian",
    ingredients: [
      { name: "Pizza dough", amount: "1", unit: "lb" },
      { name: "San Marzano tomatoes", amount: "1", unit: "can" },
      { name: "Fresh mozzarella", amount: "8", unit: "oz" },
      { name: "Fresh basil", amount: "1", unit: "bunch" },
      { name: "Olive oil", amount: "2", unit: "tbsp" },
    ],
    instructions: [
      "Preheat oven to 500°F with pizza stone inside.",
      "Stretch dough into a 12-inch circle.",
      "Spread crushed tomatoes evenly over dough.",
      "Tear mozzarella and distribute over pizza.",
      "Bake for 12-15 minutes until crust is golden.",
      "Top with fresh basil and drizzle with olive oil.",
    ],
    nutritionInfo: {
      calories: 450,
      protein: 18,
      carbs: 52,
      fat: 20,
      fiber: 3,
    },
    tags: ["italian", "vegetarian", "classic"],
    isFavorite: false,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "3",
    title: "Thai Green Curry",
    description: "Aromatic coconut curry with tender chicken, bamboo shoots, and Thai basil. Spicy, creamy, and satisfying.",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80",
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    category: "Dinner",
    cuisine: "Thai",
    ingredients: [
      { name: "Chicken breast", amount: "1", unit: "lb" },
      { name: "Green curry paste", amount: "3", unit: "tbsp" },
      { name: "Coconut milk", amount: "2", unit: "cans" },
      { name: "Bamboo shoots", amount: "1", unit: "can" },
      { name: "Thai basil", amount: "1", unit: "cup" },
    ],
    instructions: [
      "Heat oil in a wok over high heat.",
      "Add curry paste and fry for 1 minute until fragrant.",
      "Add chicken and cook until browned.",
      "Pour in coconut milk and bring to a simmer.",
      "Add bamboo shoots and cook for 15 minutes.",
      "Stir in Thai basil and serve over jasmine rice.",
    ],
    nutritionInfo: {
      calories: 380,
      protein: 28,
      carbs: 12,
      fat: 26,
      fiber: 2,
    },
    tags: ["spicy", "asian", "curry", "comfort-food"],
    isFavorite: true,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "4",
    title: "Avocado Toast with Poached Eggs",
    description: "Creamy smashed avocado on sourdough with perfectly poached eggs, chili flakes, and microgreens.",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80",
    prepTime: 10,
    cookTime: 5,
    servings: 2,
    difficulty: "Easy",
    category: "Breakfast",
    cuisine: "American",
    ingredients: [
      { name: "Sourdough bread", amount: "2", unit: "slices" },
      { name: "Ripe avocado", amount: "1", unit: "whole" },
      { name: "Eggs", amount: "2", unit: "large" },
      { name: "Chili flakes", amount: "1/4", unit: "tsp" },
      { name: "Microgreens", amount: "1/4", unit: "cup" },
    ],
    instructions: [
      "Toast sourdough bread until golden.",
      "Mash avocado with salt and pepper.",
      "Poach eggs in simmering water for 3 minutes.",
      "Spread avocado on toast and top with eggs.",
      "Garnish with chili flakes and microgreens.",
    ],
    nutritionInfo: {
      calories: 340,
      protein: 14,
      carbs: 28,
      fat: 22,
      fiber: 8,
    },
    tags: ["breakfast", "healthy", "quick", "vegetarian"],
    isFavorite: false,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-08"),
  },
  {
    id: "5",
    title: "Japanese Ramen Bowl",
    description: "Rich tonkotsu broth with tender chashu pork, soft-boiled egg, nori, and springy noodles.",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80",
    prepTime: 30,
    cookTime: 180,
    servings: 4,
    difficulty: "Hard",
    category: "Dinner",
    cuisine: "Japanese",
    ingredients: [
      { name: "Pork bones", amount: "2", unit: "lbs" },
      { name: "Ramen noodles", amount: "400", unit: "g" },
      { name: "Chashu pork", amount: "8", unit: "slices" },
      { name: "Soft-boiled eggs", amount: "4", unit: "whole" },
      { name: "Nori sheets", amount: "4", unit: "sheets" },
    ],
    instructions: [
      "Boil pork bones for 4-6 hours to create rich broth.",
      "Prepare chashu pork by braising in soy and mirin.",
      "Cook ramen noodles according to package.",
      "Assemble bowls with broth, noodles, and toppings.",
      "Garnish with nori, green onions, and sesame seeds.",
    ],
    nutritionInfo: {
      calories: 680,
      protein: 42,
      carbs: 58,
      fat: 32,
      fiber: 4,
    },
    tags: ["japanese", "soup", "comfort-food", "weekend-project"],
    isFavorite: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "6",
    title: "Fresh Greek Salad",
    description: "Crisp cucumbers, juicy tomatoes, red onion, Kalamata olives, and creamy feta with oregano dressing.",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    category: "Lunch",
    cuisine: "Greek",
    ingredients: [
      { name: "Cucumber", amount: "2", unit: "large" },
      { name: "Tomatoes", amount: "4", unit: "medium" },
      { name: "Red onion", amount: "1", unit: "small" },
      { name: "Feta cheese", amount: "200", unit: "g" },
      { name: "Kalamata olives", amount: "1", unit: "cup" },
    ],
    instructions: [
      "Chop cucumber and tomatoes into chunks.",
      "Slice red onion thinly.",
      "Combine vegetables in a large bowl.",
      "Add olives and crumble feta on top.",
      "Dress with olive oil, lemon, and oregano.",
    ],
    nutritionInfo: {
      calories: 220,
      protein: 8,
      carbs: 14,
      fat: 16,
      fiber: 3,
    },
    tags: ["salad", "healthy", "vegetarian", "no-cook", "quick"],
    isFavorite: false,
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "7",
    title: "Chocolate Lava Cake",
    description: "Decadent individual chocolate cakes with a molten center. An impressive dessert that's easier than it looks.",
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800&q=80",
    prepTime: 15,
    cookTime: 12,
    servings: 4,
    difficulty: "Medium",
    category: "Dessert",
    cuisine: "French",
    ingredients: [
      { name: "Dark chocolate", amount: "200", unit: "g" },
      { name: "Butter", amount: "100", unit: "g" },
      { name: "Eggs", amount: "4", unit: "large" },
      { name: "Sugar", amount: "100", unit: "g" },
      { name: "Flour", amount: "50", unit: "g" },
    ],
    instructions: [
      "Melt chocolate and butter together.",
      "Whisk eggs and sugar until light and fluffy.",
      "Fold chocolate mixture into eggs.",
      "Add flour and mix gently.",
      "Bake at 425°F for 12 minutes.",
      "Serve immediately with ice cream.",
    ],
    nutritionInfo: {
      calories: 420,
      protein: 8,
      carbs: 38,
      fat: 28,
      fiber: 2,
    },
    tags: ["dessert", "chocolate", "indulgent", "date-night"],
    isFavorite: true,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "8",
    title: "Chicken Tikka Masala",
    description: "Tender marinated chicken in a creamy, spiced tomato sauce. A British-Indian classic loved worldwide.",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80",
    prepTime: 30,
    cookTime: 30,
    servings: 4,
    difficulty: "Medium",
    category: "Dinner",
    cuisine: "Indian",
    ingredients: [
      { name: "Chicken thighs", amount: "1.5", unit: "lbs" },
      { name: "Yogurt", amount: "1", unit: "cup" },
      { name: "Tomato puree", amount: "400", unit: "g" },
      { name: "Heavy cream", amount: "1", unit: "cup" },
      { name: "Garam masala", amount: "2", unit: "tbsp" },
    ],
    instructions: [
      "Marinate chicken in yogurt and spices for 2 hours.",
      "Grill or broil chicken until charred.",
      "Make sauce with tomatoes, cream, and spices.",
      "Add chicken to sauce and simmer for 10 minutes.",
      "Serve with basmati rice and naan bread.",
    ],
    nutritionInfo: {
      calories: 520,
      protein: 38,
      carbs: 18,
      fat: 34,
      fiber: 3,
    },
    tags: ["indian", "curry", "comfort-food", "crowd-pleaser"],
    isFavorite: false,
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-14"),
  },
]

export const mockMealPlan: MealPlan[] = [
  {
    id: "1",
    date: "2024-01-22",
    meals: {
      breakfast: mockRecipes[3],
      lunch: mockRecipes[5],
      dinner: mockRecipes[0],
      snacks: [],
    },
  },
  {
    id: "2",
    date: "2024-01-23",
    meals: {
      breakfast: null,
      lunch: mockRecipes[1],
      dinner: mockRecipes[2],
      snacks: [],
    },
  },
  {
    id: "3",
    date: "2024-01-24",
    meals: {
      breakfast: mockRecipes[3],
      lunch: null,
      dinner: mockRecipes[7],
      snacks: [],
    },
  },
  {
    id: "4",
    date: "2024-01-25",
    meals: {
      breakfast: null,
      lunch: mockRecipes[5],
      dinner: mockRecipes[4],
      snacks: [],
    },
  },
  {
    id: "5",
    date: "2024-01-26",
    meals: {
      breakfast: mockRecipes[3],
      lunch: null,
      dinner: mockRecipes[1],
      snacks: [mockRecipes[6]],
    },
  },
  {
    id: "6",
    date: "2024-01-27",
    meals: {
      breakfast: null,
      lunch: mockRecipes[5],
      dinner: mockRecipes[0],
      snacks: [],
    },
  },
  {
    id: "7",
    date: "2024-01-28",
    meals: {
      breakfast: mockRecipes[3],
      lunch: mockRecipes[1],
      dinner: mockRecipes[2],
      snacks: [mockRecipes[6]],
    },
  },
]

export const categories = [
  "All",
  "Breakfast",
  "Lunch",
  "Dinner",
  "Dessert",
  "Snacks",
  "Appetizers",
]

export const cuisines = [
  "All",
  "American",
  "Italian",
  "Mediterranean",
  "Thai",
  "Japanese",
  "Indian",
  "Greek",
  "French",
  "Mexican",
]
